### ISSUE TITLE
Sync with multiple devices and backup to cloud

### ISSUE THREAD

**Issue by bocharsky-bw** [gammons/todolist#2]
Hey, nice project! I just have few questions at first glance:

- How can I backup my TODOs to the cloud, i.e. to the Google Drive, Dropbox, etc?
- Is it possible to sync my TODO list with multiple devices? I mean, I have a few laptops where I want to have the same TODO list. If I add more TODOs on one laptop - it automatically sync with the second one and I can see added TODOs on the second laptop too.

**Comment by gammons** [comment]
Hey Victor,  glad you like it!

So I do the same thing right now because I tend to dual boot between Mac OS and Linux, depending on my mood.  I sync my main todo list in my home dir via dropbox.  My .todos.json file is just symlinked to a file in my dropbox dir.

```sh
~ ls -la .todos.json
lrwxrwxrwx 1 grant users 36 Apr 18 08:37 .todos.json -> /home/grant/Dropbox/todos/todos.json
```
That way, dropbox syncs .todos.json between the two systems and they are in sync.

I was thinking about doing something with a Firebase backend at some point, but I decided to back out for time reasons.  And, the more I thought about it, I like the simplicity of the tool right now.  It's just a file, and there are plenty of ways of syncing files between computers right now.
