### ISSUE TITLE
Help wanted:  Implement using ~/.todos.json by default

### ISSUE THREAD

**Issue by gammons** [gammons/todolist#31]
Per the comments of multiple users, I think we should implement this workflow:

1. when running todolist, see if a `.todos.json` exists in the current working directory.
2. If yes, use that `.todos.json`.
3. If no, use `~/.todos.json`.

Also, add documentation to the `gh-pages` branch to let users know this is how the app works.

PRs welcome!

**Comment by waldyrious** [comment]
For reference, there's been some related code and discussion in #13.

**Comment by NonerKao** [comment]
I post a PR first and need your feedback.  If it is OK then I'll make the `gh-pages` part later.

**Comment by gammons** [comment]
@NonerKao please update `gh-pages` when you get a chance.

**Comment by NonerKao** [comment]
#41 I'm sorry for the serious mistake that should have been taken care of.

I follow your suggestion and do some local test, but it fails many tests.  The reason is that, if the location check is made in `f.Load()`, it will overwrite the `f.FileLocation`  in those tests, which is mostly called `todos.json` rather than `.todos.json`, with home repository. 

Although the value of `f.FileLocation` is given when `NewFileStore` is called, it is not referenced until any `a.Load`.  So I propose commit #42 to fix this without changing all those tests, which containes:

* in `NewFileStore()`: set `FileLocation` default to ""
* new private function `getLocation()`: the main logic, those that were in `NewFileStore()`
* in `Load()`: call `getLocation()` to assign a value to `f.FileLocation`
* in `Initialize()`: check ".todos.json" instead of `f.FileLocation`

I apologize again for all the inconvenience.

**Comment by gammons** [comment]
I'll be getting to this today.

**Comment by gammons** [comment]
Merged #42 and I am releasing 0.5.2 now.
