### ISSUE TITLE
Tasks entered via browser not being numbered in console

### ISSUE THREAD

**Issue by marcelluseasley** [gammons/todolist#33]
When I add tasks via the web (after issuing todolist web), and return to the command line and enter: todolist list, the tasks that were added via the browser are not numbered. Instead they all have a value of 0. As a result, if you enter todolist d 0, it will just delete the highest task in the list with a 0 next to it.

[screenshot](https://pbs.twimg.com/media/C4oaeI2W8Ag0Nmv.jpg)

**Comment by marcelluseasley** [comment]
I was attempting to track down the bug, but it appears that the code to handle adding tasks via the web is done in Javascript, and in an S3 bucket.

**Comment by NonerKao** [comment]
Thanks for the report.
We will check this bug ASAP.

PRs are welcome!

**Comment by NonerKao** [comment]
@gammons 
Currently the web interface requires the use of network connection so that it can receive necessary files such as style sheets and script files.  It turns out that bugs in those out-of-repo files are not fixable.

While there is still ways to fix this, I think it is more elegant to include those remote files into the source first, and then fix them accordingly.  
Any comments?

**Comment by gammons** [comment]
@marcelluseasley sorry for the delay here.  I just pushed a fix for this now.  it's available in 0.5.3 of todolist.
