### ISSUE TITLE
Empty web view

### ISSUE THREAD

**Issue by loranger** [gammons/todolist#44]
Hello,

It seems the web view does not work anymore :
The external resources returns a 404 error code

![Empty web view](http://take.ms/S2l9M)

Or maybe I misunderstood something ?

**Comment by gammons** [comment]
oh jeez @loranger you're totally right!  I just uploaded the assets for the web view for 0.5.1.  It should work now.

**Comment by gammons** [comment]
closing for now.  re-open if it is still not working.

**Comment by loranger** [comment]
That's perfect, thank you so much !

**Comment by asidiali** [comment]
Getting this same issue, `404`ing on `../0.5.3/main.css`. Thanks for the help.

**Comment by gammons** [comment]
Fixed now @asidiali .  The problem here is that I need to remember to release the frontend as well as the todolist backend, since they are 2 separate projects tied by version number.  So far I've failed to do that twice, so I need to devise a way to remember next time.  Maybe tattooing instructions to my arm?

**Comment by asidiali** [comment]
Gotcha well thanks @gammons for the quick fix, as well as the solid todo tool. I'm studying Go currently and would love to contribute in the near future - going to attempt #50 and submit a PR if I make something worthwhile happen. Cheers 🤙🏼
