### ISSUE TITLE
Port forwarding rendering default .todos.json 

### ISSUE THREAD

**Issue by dainmiller** [gammons/todolist#46]
Hey there,

Replication steps:
* Add some todos, launch local web server
* Verify locally you can see your new custom todos
* `ngrok http PORT` and open new live URL
* You will see a default list of .todos.json here, not the user generated todos

I also tried with other port forwarding services https://forwardhq.com/ etc and same result. 

Figure I can leave port forwarding running on my local machine to use this on my phone, but need to first figure out how to get user generated todos rendering. :)

**Comment by gammons** [comment]
Hi @dainmiller wow, I never thought to do that!  I guess the only issue there is security.

The reason is because when the frontend [chooses which backend strategy](https://github.com/gammons/todolist_frontend/blob/master/app/sagas.js#L11) to use, it looks at `window.location` specifically for `localhost`.  There's a [cool demo](http://demo.todolist.site) of the todolist frontend, which are the demo todos that the `TestBackend` automagically generates.

Let me see if I can get something working now.  Hold please!

**Comment by gammons** [comment]
ok @dainmiller confirmed ngrok now works, albeit with http and not https.  You should be good to go ;)

**Comment by dainmiller** [comment]
Confirming it works! Thanks so much @gammons, really appreciate the quick help. Loving this tool. One of the most elegant and high quality UX's on a command line utility I've used.

**Comment by gammons** [comment]
Thanks!  That means a lot to me!

**Comment by gammons** [comment]
@dainmiller one gotcha that occurred to me if you're using the web view in a more permanent fashion - if you update your todolist on the command line, those changes will not update on the web automatically.  Maybe someday they will, but it's not bi-directional right now.
