### ISSUE TITLE
Feature Request: Sync across devices

### ISSUE THREAD

**Issue by hashd** [gammons/todolist#71]
A command line gtd todo manager is exactly the sort of thing I'm looking for but would it be possible to add syncing your tasks feature for those who have to work on multiple devices like me?

**Comment by patillacode** [comment]
Hi @hashd 

I thought the same thing, so what I did was, since this uses a file called `.todos.json` in your home folder as the main todolist, I have created a link into my cloud service of choice (owncloud, dropbox) 

something like `ln -s /path/to/could/folder/todos.json ~/.todos.json`

That would do the trick.

**Comment by gammons** [comment]
I use dropbox with a symlinked .todos.json and it works great across devices.  See #43 for more info.

**Comment by hashd** [comment]
Perfect. Thanks :)
