### ISSUE TITLE
Unable to access remotely with web interface

### ISSUE THREAD

**Issue by asegner** [gammons/todolist#81]
Using the dockerfile to create a container. Works well when accessing browser locally. Does not work when accessing todo list web service from another machine (not localhost). Appears links on the page are always generated with localhost as host name. When I attempt to access remotely, the page is attempting to access http://localhost:7890/todos instead of http://[hostname]:7890/todos. The page displays an error stating "A backend failure occurred". http://[hostname]:7890/todos does provide proper json output.

**Comment by NonerKao** [comment]
Since we do not have any authentication mechanism embedded in this software, so once you expose the todolist container to public, it would be very dangerous.

However, you can still accomplish what you intend to do by offering docker command-line argument `-P`, which expose the same port on the remote host.

**Comment by gammons** [comment]
let us know if you need more help here.
