### ISSUE TITLE
strikethrough completed tasks

### ISSUE THREAD

**Issue by gwelr** [gammons/todolist#96]
when listing todos, if one have a long list of todos as I have, the space between the brackets (todos state) and the todo description makes it difficult to see which todo is done and which is not yet done. 

One easy solution (and common ui pattern) would be to strikethrough the task description. 

The ANSI/VT100 terminals and terminal emulators are not just able to display black and white  or color text; they can display formatted texts thanks to escape sequences. 

The following `echo -e "\e[9mstrikethrough\e[0m"`would display the text "strikethrough"  well... striked through.

**Comment by NonerKao** [comment]
It is somehow paradoxical to highlight the descriptions that a user is interested in using strike-through.  Even if we have to rely on the terminal features, underscore or reverse-color seems better to me.

No offense, but have you tried to categorize your todos into different projects, so that you can use `todolist l by p` to prevent very long output?

**Comment by NonerKao** [comment]
Closed.
Please feel free to reopen this issue if necessary.
